# Generated by Django 5.2.3 on 2025-06-26 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OFF', 'Off'), ('ON', 'On'), ('ERR', 'Error')], default='OFF', max_length=3)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_param', models.PositiveIntegerField(default=0, help_text='Example numeric parameter', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
